### ISSUE TITLE
Use pep8 compliant module names

### ISSUE THREAD

**Issue by jayvdb** [AbdealiJK/pycolorname#12]
"Modules should have short, all-lowercase names. Underscores can be used in the module name if it improves readability."
https://www.python.org/dev/peps/pep-0008/#package-and-module-names

**Comment by AbdealiJK** [comment]
I'm surprised that the PEP8 linter I'm using didn't catch this.
Will do

**Comment by jayvdb** [comment]
The linter for naming is https://pypi.python.org/pypi/pep8-naming
