### ISSUE TITLE
README in pypi - change to rst

### ISSUE THREAD

**Issue by AbdealiJK** [AbdealiJK/pycolorname#20]
Not sure which parser the README on the pypi page uses.
But it doesnt look like how it looks on github..

https://pypi.python.org/pypi/pycolorname

**Comment by jayvdb** [comment]
It uses a very strict RST parser, not MD.

**Comment by AbdealiJK** [comment]
Sounds right.
Here's the appropriate issue asking for support on markdown - https://bitbucket.org/pypa/pypi/issues/148/support-markdown-for-readmes

Not implemented yet. Seems like we'll be moving to RST then
