### ISSUE TITLE
Credit contributors better

### ISSUE THREAD

**Issue by AbdealiJK** [AbdealiJK/pycolorname#21]
- Where else should we credit developers ?
 - Who are the other (older) developers ? 
 - How do we mention the sources ?

**Comment by jayvdb** [comment]
Usually the list of contributors appears in a file called `CREDITS` (see pywikibot-core)

It would be nice for the readme to indicate this package was derived from http://git.wikimedia.org/log/pywikibot%2Fpycolorname.git , which was extracted out of http://git.wikimedia.org/log/pywikibot%2Fcompat.git .  The fun part would be finding where the code was in the compat repo. (`git log -S ...` can probably help find where & when the code was removed)

We only know of older/other contributor DrTrigon (the addition of .gitreview was not relevant), however in the `compat` repo we may find that other people also contributed to the code.
