### ISSUE TITLE
Add better docs

### ISSUE THREAD

**Issue by AbdealiJK** [AbdealiJK/pycolorname#23]
We need:

 - Usage information in readme
 - Installation information in readme
 - readthedocs integration

**Comment by AbdealiJK** [comment]
Do we really need a full fledged docs ? I cant think of anything more to say other than whats in the readme

**Comment by AbdealiJK** [comment]
@jayvdb could you help me out here ? Is the README sufficient ?
Could you go through the readme and check if there is something you do not understand ?
Is there anything that needs to be added ?

Is a complete documentation on readthedocs required in your opinion ?

**Comment by jayvdb** [comment]
The readme looks good enough. readthedocs would be useful, but very low priority, and probably better done after this package has been used by a real program like `catimages.py`.

**Comment by AbdealiJK** [comment]
Alright then,

Closing this for now.
Will repoen later if required.
